/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KassaDialog.java
 *
 * Created on Aug 8, 2009, 4:47:22 PM
 */

package com.artivisi.pos.ui.dialog.master;

import com.artivisi.pos.model.master.Kassa;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.artivisi.pos.util.ApplicationUtils;
import com.artivisi.pos.util.TextComponentUtils;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.Problems;
import org.netbeans.validation.api.Validator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationListener;
import org.netbeans.validation.api.ui.ValidationStrategy;

/**
 *
 * @author ifnu
 */
public class KassaDialog extends javax.swing.JDialog {

    private Kassa kassa;
    private SimpanKassaValidator validator = new SimpanKassaValidator();
    private SimpanKassaValidationListener listener = new SimpanKassaValidationListener();
    /** Creates new form KassaDialog */
    public KassaDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);

        TextComponentUtils.setAutoUpperCaseText(10, txtIdKassa);
        TextComponentUtils.setAutoUpperCaseText(25, txtNamaKassa);
        TextComponentUtils.setAutoUpperCaseText(255, txtDeskripsiKassa);

        initValidation();
    }

    private void initValidation(){
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(txtIdKassa, ValidationStrategy.DEFAULT,
                Validators.REQUIRE_NON_EMPTY_STRING);
        group.add(txtNamaKassa, ValidationStrategy.DEFAULT,
                Validators.REQUIRE_NON_EMPTY_STRING);
        group.add(listener);
        validationPanel.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                if(validationPanel.getProblem() == null){
                    btnOk.setEnabled(true);
                } else {
                    btnOk.setEnabled(false);
                }
            }
        });
    }

    public Kassa showDialog(){
        //baca properties untuk kassa
        Kassa k = ApplicationUtils.kassaSetting();
        if(k!=null){
            txtDeskripsiKassa.setText(k.getDeskripsi());
            txtIdKassa.setText(k.getId());
            txtNamaKassa.setText(k.getNama());
            //TODO dapatkan IP local
        }
        setVisible(true);
        return kassa;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        validationPanel = new org.netbeans.validation.api.ui.ValidationPanel();
        btnOk = new javax.swing.JButton();
        txtIdKassa = new javax.swing.JTextField();
        txtNamaKassa = new javax.swing.JTextField();
        txtDeskripsiKassa = new javax.swing.JTextField();
        txtIp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Kassa (unik)");

        jLabel2.setText("Nama Kassa");

        jLabel3.setText("Deskripsi");

        jLabel4.setText("IP");

        btnOk.setText("OK");
        btnOk.setEnabled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        txtIdKassa.setName("ID Kassa"); // NOI18N

        txtNamaKassa.setName("Nama Kassa"); // NOI18N

        txtDeskripsiKassa.setName("Deskripsi"); // NOI18N

        txtIp.setEnabled(false);

        jLabel5.setText("<html>Client ini belum memiliki informasi tentang Kassa.<br/>Lengkapi informasi di bawah ini dan pastikan ID Kassa unik</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(validationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdKassa, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaKassa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeskripsiKassa, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdKassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaKassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeskripsiKassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean gagalSimpan = false;

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        kassa = new Kassa();
        kassa.setDeskripsi(txtDeskripsiKassa.getText());
        kassa.setId(txtIdKassa.getText());
        kassa.setNama(txtNamaKassa.getText());
        kassa.setLocalIp(txtIp.getText());
        Boolean r = FrameUtama.getMasterService().simpan(kassa);
        if(r == false){
            listener.simpanGagal();
            gagalSimpan = true;
        } else {
            gagalSimpan = false;
            //Simpan di dalam user.home
            String userHome = System.getProperty("user.home");
            File posDir = new File(userHome + File.separatorChar + ".pos");
            if(!posDir.exists()){
                posDir.mkdir();
            }
            File kassaFile = new File(userHome + File.separatorChar + ".pos" + File.separatorChar + "kassa.properties");
            Properties p = new Properties();
            p.setProperty("id_kassa", kassa.getId());
            p.setProperty("nama_kassa", kassa.getNama());
            p.setProperty("deskripsi_kassa", kassa.getDeskripsi());
            p.setProperty("ip_kassa", kassa.getLocalIp());
            try {
                p.store(new FileWriter(kassaFile), "simpan kassa");
            } catch (IOException ex) {
                listener.simpanGagal();
            }
            dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private class SimpanKassaValidator implements Validator<Kassa>{

        public boolean validate(Problems problems, String componentName, Kassa kassa) {
            if(gagalSimpan){
                problems.add("Gagal menyimpan kassa. Hubungi sistem administrator anda!");
            }
            return false;
        }

    }

    private class SimpanKassaValidationListener extends ValidationListener{

        @Override
        public boolean validate(Problems problems) {
            return validator.validate(problems, "Simpan Kassa", kassa);
        }

        public void simpanGagal(){
            this.validate();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDeskripsiKassa;
    private javax.swing.JTextField txtIdKassa;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtNamaKassa;
    private org.netbeans.validation.api.ui.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables

}
