/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProdukSearchDialog.java
 *
 * Created on Jul 1, 2009, 3:46:15 PM
 */

package com.artivisi.pos.ui.dialog.master;

import com.artivisi.pos.model.master.Produk;
import com.artivisi.pos.model.master.PulsaElektrik;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.artivisi.pos.util.BigDecimalRenderer;
import com.artivisi.pos.util.TextComponentUtils;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author ifnu
 */
public class ProdukDanPulsaElektrikSearchDialog extends javax.swing.JDialog {

    private List datas;
    private Object selectedProduk;
    private boolean isOk = false;

    /** Creates new form ProdukSearchDialog */
    public ProdukDanPulsaElektrikSearchDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);
        tblProduk.getSelectionModel().addListSelectionListener(new ProdukSelectionListener());
        tblProduk.setAutoCreateColumnsFromModel(false);
        tblProduk.setDefaultRenderer(BigDecimal.class, new BigDecimalRenderer());
    }

    public Object showDialog(){
        List<Produk> produks = FrameUtama.getMasterService().semuaProdukNonPulsaElektrik();
        List<PulsaElektrik> pulsaElektriks = FrameUtama.getMasterService().semuaPulsaElektrik();
        datas = new ArrayList();
        datas.addAll(produks);
        datas.addAll(pulsaElektriks);
        Collections.sort(datas,new ProdukDanPulsaElektrik());
        tblProduk.setModel(new ProdukTableModel());
        setVisible(true);
        if(isOk == false) selectedProduk = null;
        return selectedProduk;
    }

    private class ProdukDanPulsaElektrik implements Comparator{

        public int compare(Object o1, Object o2) {
            if(o1 instanceof Produk && o2 instanceof Produk){
                return ((Produk)o1).getId().compareTo(((Produk)o2).getId());
            } else if(o1 instanceof Produk && o2 instanceof PulsaElektrik){
                return ((Produk)o1).getId().compareTo(((PulsaElektrik)o2).getId());
            } else if(o1 instanceof PulsaElektrik && o2 instanceof PulsaElektrik){
                return ((PulsaElektrik)o1).getId().compareTo(((PulsaElektrik)o2).getId());
            } else if(o1 instanceof PulsaElektrik && o2 instanceof Produk){
                return ((PulsaElektrik)o1).getId().compareTo(((Produk)o2).getId());
            }
            return 0;
        }
        
    }

    private class ProdukTableModel extends AbstractTableModel{

        public int getRowCount() {
            return datas.size();
        }

        public int getColumnCount() {
            return 6;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            Object o = datas.get(rowIndex);
            if(o instanceof Produk){
                Produk p = (Produk) o;
                switch(columnIndex){
                    case 0 : return p.getNama();
                    case 1 : return p.getId();
                    case 2 : return p.getSatuan();
                    case 3 : return p.getHargaPokok();
                    case 4 : return p.getHargaJual();
                    case 5 : return p.getStok();
                    default: return "";
                }
            } else if (o instanceof PulsaElektrik){
                PulsaElektrik p = (PulsaElektrik) o;
                switch(columnIndex){
                    case 0 : return p.getNama();
                    case 1 : return p.getId();
                    case 2 : return p.getProduk().getSatuan();
                    case 3 : return p.getProduk().getHargaPokok();
                    case 4 : return p.getHargaJual();
                    case 5 : return p.getProduk().getStok();
                    default: return "";
                }
            } else {
                return "";
            }
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch(columnIndex){
                case 4 : return BigDecimal.class;
                case 5 : return Integer.class;
                default : return String.class;
            }
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cari Produk");

        jLabel1.setText("Search");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kode Produk", "Satuan", "Harga Pokok", "Harga Jual", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tblProduk);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        if(evt.getKeyChar() == KeyEvent.VK_ESCAPE) {
            selectedProduk = null;
            dispose();
        }
        for(int i=0;i<tblProduk.getRowCount();i++){
            String current = tblProduk.getValueAt(i, 0).toString();
            if(current.toLowerCase().indexOf(txtCari.getText().toLowerCase())>=0){
                tblProduk.getSelectionModel().setSelectionInterval(i, i);
                tblProduk.getColumnModel().getSelectionModel().setSelectionInterval(0, 0);
                TextComponentUtils.scrollToRect(tblProduk, i);
                break;
            }
        }

}//GEN-LAST:event_txtCariKeyReleased

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        isOk = true;
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        selectedProduk = null;
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed
    private class ProdukSelectionListener implements ListSelectionListener{
        public void valueChanged(ListSelectionEvent e) {
            if(tblProduk.getSelectedRow()>=0){
                int indexModel = tblProduk.convertRowIndexToModel(tblProduk.getSelectedRow());
                selectedProduk = datas.get(indexModel);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

}
