/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SatuanSearchDialog.java
 *
 * Created on Jul 1, 2009, 3:46:15 PM
 */

package com.artivisi.pos.ui.dialog.master;

import com.artivisi.pos.model.master.Satuan;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.artivisi.pos.util.TextComponentUtils;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author ifnu
 */
public class SatuanSearchDialog extends javax.swing.JDialog {

    private List<Satuan> Satuans;
    private Satuan selectedSatuan;
    private boolean isOk = false;

    /** Creates new form SatuanSearchDialog */
    public SatuanSearchDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);
        tblSatuan.getSelectionModel().addListSelectionListener(new SatuanSelectionListener());
        tblSatuan.setAutoCreateColumnsFromModel(false);
    }

    public Satuan showDialog(){
        Satuans = FrameUtama.getMasterService().semuaSatuan();
        tblSatuan.setModel(new SatuanTableModel());
        setVisible(true);
        if(isOk == false) selectedSatuan = null;
        return selectedSatuan;
    }

    private class SatuanTableModel extends AbstractTableModel{

        public int getRowCount() {
            return Satuans.size();
        }

        public int getColumnCount() {
            return 2;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            Satuan p = Satuans.get(rowIndex);
            switch(columnIndex){
                case 0 : return p.getNama();
                case 1 : return p.getId();
                default: return "";
            }
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSatuan = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cari Produk");

        jLabel1.setText("Search");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tblSatuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kode Satuan"
            }
        ));
        jScrollPane1.setViewportView(tblSatuan);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        for(int i=0;i<tblSatuan.getRowCount();i++){
            String current = tblSatuan.getValueAt(i, 0).toString();
            if(current.toLowerCase().indexOf(txtCari.getText().toLowerCase())>=0){
                tblSatuan.getSelectionModel().setSelectionInterval(i, i);
                tblSatuan.getColumnModel().getSelectionModel().setSelectionInterval(0, 0);
                TextComponentUtils.scrollToRect(tblSatuan, i);
                break;
            }
        }
}//GEN-LAST:event_txtCariKeyReleased

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        isOk = true;
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        selectedSatuan = null;
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed
    private class SatuanSelectionListener implements ListSelectionListener{
        public void valueChanged(ListSelectionEvent e) {
            if(tblSatuan.getSelectedRow()>=0){
                int indexModel = tblSatuan.convertRowIndexToModel(tblSatuan.getSelectedRow());
                selectedSatuan = Satuans.get(indexModel);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSatuan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

}
