/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuDialog.java
 *
 * Created on May 28, 2009, 1:18:46 PM
 */

package com.artivisi.pos.ui.dialog.sekuriti;

import com.artivisi.pos.model.sekuriti.Menu;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.artivisi.pos.util.TextComponentUtils;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ifnu
 */
public class MenuDialog extends javax.swing.JDialog {

    /** Creates new form MenuDialog */
    public MenuDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);

        TextComponentUtils.setNumericTextOnly(txtLevel);
        TextComponentUtils.setNumericTextOnly(txtUrutan);

        List<Menu> menus = FrameUtama.getSekuritiService().semuaMenu();
        List<Menu> currentMenus = null;
        for(Menu m : menus){
            currentMenus = menuMap.get(m.getMenuLevel());
            if(currentMenus==null){
                currentMenus = new ArrayList<Menu>();
                currentMenus.add(m);
                menuMap.put(m.getMenuLevel(), currentMenus);
            } else {
                currentMenus.add(m);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtPanelClass = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        cmbParent = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtUrutan = new javax.swing.JTextField();
        btnOke = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Panel Class");

        jLabel3.setText("Level");

        jLabel4.setText("Parent Menu");

        txtLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLevelKeyReleased(evt);
            }
        });

        jLabel5.setText("Urutan");

        btnOke.setText("OK");
        btnOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPanelClass, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtLevel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUrutan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnOke)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(cmbParent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPanelClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUrutan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOke)
                    .addComponent(btnBatal))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLevelKeyReleased
        if(txtLevel.getText().length()>0){
            Integer level = Integer.valueOf(txtLevel.getText());
            if(level!= null){
                List<Menu> currents = menuMap.get(level-1);
                if(currents!=null && !currents.isEmpty()){
                    cmbParent.setModel(new DefaultComboBoxModel(currents.toArray()));
                } else {
                    cmbParent.removeAll();
                }
            }
        }
    }//GEN-LAST:event_txtLevelKeyReleased

    private void btnOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeActionPerformed
        if(validateForm()){
            if(menu==null) menu = new Menu();
            loadFormToModel();
            dispose();
        }
    }//GEN-LAST:event_btnOkeActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        menu = null;
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private Menu menu;
    private Map<Integer,List<Menu>> menuMap= new HashMap<Integer, List<Menu>>();

    public Menu showDialog(){
        setVisible(true);
        return menu;
    }
    public Menu showDialog(Menu menu){
        this.menu = menu;
        loadModelToForm();
        setVisible(true);
        return menu;
    }

    private void loadModelToForm(){
        txtNama.setText(menu.getId());
        txtLevel.setText(String.valueOf(menu.getMenuLevel()));
        txtPanelClass.setText(menu.getPanelClass());
        txtUrutan.setText(String.valueOf(menu.getUrutan()));
        if(menu.getMenuLevel()!=null){
            List<Menu> currentMenus = menuMap.get(menu.getMenuLevel()-1);
            if(currentMenus!=null && !currentMenus.isEmpty()){
                cmbParent.setModel(new DefaultComboBoxModel(currentMenus.toArray()));
                if(currentMenus.contains(menu.getParent())){
                    cmbParent.setSelectedItem(menu.getParent());
                } else {
                    cmbParent.setSelectedItem(null);
                }
            }
        }
    }

    private void loadFormToModel(){
        menu.setId(txtNama.getText());
        menu.setMenuLevel(Integer.valueOf(txtLevel.getText()));
        menu.setPanelClass(txtPanelClass.getText());
        menu.setUrutan(Integer.valueOf(txtUrutan.getText()));
        menu.setParent((Menu) cmbParent.getSelectedItem());
    }

    private boolean validateForm(){
        if(txtLevel.getText().length()>0 &&
                txtNama.getText().length()>0 &&
                txtUrutan.getText().length()>0){
            if(txtPanelClass.getText().length()>0){
                try {
                        Object instance = Class.forName(txtPanelClass.getText()).newInstance();
                        if(instance==null || !( instance instanceof JInternalFrame)){
                            throw new Exception("bukan Internalframe");
                        }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(FrameUtama.getInstance(), 
                            "class " + txtPanelClass.getText() + " tidak ditemukan atau bukan Subclass JInternalFrame!",
                            "Error",JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
            if(Integer.valueOf(txtLevel.getText())>0 && cmbParent.getSelectedItem()==null){
                JOptionPane.showMessageDialog(FrameUtama.getInstance(),
                        "Menu dengan level >0 harus punya parent",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(FrameUtama.getInstance(), "Lengkapi form terlebih dahulu",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOke;
    private javax.swing.JComboBox cmbParent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPanelClass;
    private javax.swing.JTextField txtUrutan;
    // End of variables declaration//GEN-END:variables

}
