/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GantiKataSandiDialog.java
 *
 * Created on May 10, 2009, 10:52:04 PM
 */

package com.artivisi.pos.ui.dialog.sekuriti;

import com.artivisi.pos.model.sekuriti.Pengguna;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.twmacinta.util.MD5;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author ifnu
 */
public class UbahKataSandiDialog extends javax.swing.JDialog {

    /** Creates new form GantiKataSandiDialog */
    public UbahKataSandiDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKataSandi = new javax.swing.JPasswordField();
        txtPengguna = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKataSandi1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtKataSandi2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama Pengguna");

        jLabel2.setText("Kata Sandi Lama");

        txtKataSandi.setEchoChar(' ');

        txtPengguna.setEnabled(false);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel3.setText("Kata Sandi Baru");

        txtKataSandi1.setEchoChar(' ');

        jLabel4.setText("Ulang Kata Sandi Baru");

        txtKataSandi2.setEchoChar(' ');

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKataSandi)
                        .addComponent(txtKataSandi1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(txtKataSandi2)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKataSandi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKataSandi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showDialog(){
        setVisible(true);
    }

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if(validateForm()){
            Pengguna pengguna = FrameUtama.getPengguna();
            String kataSandiLama = pengguna.getKataSandi();
            pengguna.setKataSandi(new MD5(new String(txtKataSandi.getPassword())).asHex());
            boolean berhasil = FrameUtama.getSekuritiService().simpan(pengguna);
            if(!berhasil){
                pengguna.setKataSandi(kataSandiLama);
                JOptionPane.showMessageDialog(FrameUtama.getInstance(), "Ubah kata sandi gagal! hubungi administrator anda",
                        "Error",JOptionPane.ERROR_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private boolean validateForm(){
        String kataSandi = new MD5(new String(txtKataSandi.getPassword())).asHex();
        if(kataSandi==null || !kataSandi.equals(FrameUtama.getPengguna().getKataSandi())){
            JOptionPane.showMessageDialog(FrameUtama.getInstance(), "Kata sandi salah!"
                    ,"Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!Arrays.equals(txtKataSandi1.getPassword(),txtKataSandi2.getPassword())){
            JOptionPane.showMessageDialog(FrameUtama.getInstance(), "Kata sandi baru tidak sama!"
                    ,"Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtKataSandi;
    private javax.swing.JPasswordField txtKataSandi1;
    private javax.swing.JPasswordField txtKataSandi2;
    private javax.swing.JTextField txtPengguna;
    // End of variables declaration//GEN-END:variables

}
