package com.googlecode.projecttemplate.pos.ui;

import com.googlecode.projecttemplate.pos.ui.reports.DailySalesReportPanel;
import com.googlecode.projecttemplate.pos.ui.security.PersonPanel;
import com.googlecode.projecttemplate.pos.ui.transaction.SalesPanel;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import org.apache.log4j.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jun 19, 2010, 11:20:49 PM
 */

/**
 *
 * @author ifnu
 */
public class MainFrame extends javax.swing.JFrame {

    private static final Logger log = Logger.getLogger(MainFrame.class);

    /** Creates new form NewJFrame */
public MainFrame() {
    initComponents();
    setExtendedState(JFrame.MAXIMIZED_BOTH);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuMasterData = new javax.swing.JMenu();
        mnuPerson = new javax.swing.JMenuItem();
        mnuTransaction = new javax.swing.JMenu();
        mnuSales = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        mnuDailySalesReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi POS Toko Bangkit");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        mnuMasterData.setText("Master Data");

        mnuPerson.setText("Pengguna");
        mnuPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPersonActionPerformed(evt);
            }
        });
        mnuMasterData.add(mnuPerson);

        jMenuBar1.add(mnuMasterData);

        mnuTransaction.setText("Transaksi");

        mnuSales.setText("Penjualan");
        mnuSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalesActionPerformed(evt);
            }
        });
        mnuTransaction.add(mnuSales);

        jMenuBar1.add(mnuTransaction);

        mnuReport.setText("Laporan");

        mnuDailySalesReport.setText("Laporan Penjualan Harian");
        mnuDailySalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDailySalesReportActionPerformed(evt);
            }
        });
        mnuReport.add(mnuDailySalesReport);

        jMenuBar1.add(mnuReport);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public PersonPanel personPanel;

    private void mnuPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPersonActionPerformed
        try {
            if (personPanel == null) {
                personPanel = new PersonPanel();
                desktopPane.add(personPanel);
            } else {
                personPanel.toFront();
            }
            personPanel.setVisible(true);
            personPanel.setSelected(true);
            personPanel.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            log.error("error ketika menampilkan person panel", ex);
        }
    }//GEN-LAST:event_mnuPersonActionPerformed

    public SalesPanel salesPanel;
    private void mnuSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalesActionPerformed
        try {
            if (salesPanel == null) {
                salesPanel = new SalesPanel();
                desktopPane.add(salesPanel);
            } else {
                salesPanel.toFront();
            }
            salesPanel.setVisible(true);
            salesPanel.setSelected(true);
            salesPanel.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            log.error("error ketika menampilkan sales panel", ex);
        }
    }//GEN-LAST:event_mnuSalesActionPerformed

    public DailySalesReportPanel dailySalesReportPanel;
    private void mnuDailySalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDailySalesReportActionPerformed
       try {
            if (dailySalesReportPanel == null) {
                dailySalesReportPanel = new DailySalesReportPanel();
                desktopPane.add(dailySalesReportPanel);
            } else {
                dailySalesReportPanel.toFront();
            }
            dailySalesReportPanel.setVisible(true);
            dailySalesReportPanel.setSelected(true);
            dailySalesReportPanel.setSize(desktopPane.getSize());
        } catch (PropertyVetoException ex) {
            log.error("error ketika menampilkan sales panel", ex);
        }
    }//GEN-LAST:event_mnuDailySalesReportActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuDailySalesReport;
    private javax.swing.JMenu mnuMasterData;
    private javax.swing.JMenuItem mnuPerson;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JMenuItem mnuSales;
    private javax.swing.JMenu mnuTransaction;
    // End of variables declaration//GEN-END:variables

}
