/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PenjualanAddDialog.java
 *
 * Created on Jul 1, 2009, 3:39:14 PM
 */

package com.artivisi.pos.ui.dialog.transaksi;

import com.artivisi.pos.model.master.Produk;
import com.artivisi.pos.model.transaksi.PembelianDetail;
import com.artivisi.pos.ui.dialog.master.ProdukSearchDialog;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.artivisi.pos.util.TextComponentUtils;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author ifnu
 */
public class PembelianAddDialog extends javax.swing.JDialog {

    private PembelianDetail pembelianDetail;
    private Produk selectedProduk;
    /** Creates new form PenjualanAddDialog */
    public PembelianAddDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);

        TextComponentUtils.setCurrency(txtHargaBeli);
        TextComponentUtils.setNumericTextOnly(txtQuantity);

    }
    public PembelianDetail showDialog(){
        setVisible(true);
        return pembelianDetail;
    }
    public PembelianDetail showDialog(PembelianDetail pembelianDetail){
        this.pembelianDetail = pembelianDetail;
        loadDomainToForm();
        setVisible(true);
        return this.pembelianDetail;
    }
    private void loadDomainToForm(){
        selectedProduk = pembelianDetail.getProduk();
        txtProduk.setText(selectedProduk.getNama());
        txtQuantity.setText(pembelianDetail.getKuantitas().toString());
        txtHargaBeli.setText(
            TextComponentUtils.formatNumber(pembelianDetail.getHarga()));
        txtSubTotal.setText(
            TextComponentUtils.formatNumber(pembelianDetail.getSubTotal()));
    }
    private void loadFormToDomain(){
        pembelianDetail.setProduk(selectedProduk);
        pembelianDetail.setHarga(
            TextComponentUtils.parseNumberToBigDecimal(txtHargaBeli.getText()));
        pembelianDetail.setSubTotal(
            TextComponentUtils.parseNumberToBigDecimal(txtSubTotal.getText()));
        pembelianDetail.setKuantitas(Integer.valueOf(txtQuantity.getText()));
    }

    private boolean validateForm(){
        if(txtProduk.getText().length() == 0 || selectedProduk==null){
            JOptionPane.showMessageDialog(FrameUtama.getInstance(),
                    "Pilih produk terlebih dahulu!","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(txtHargaBeli.getText().length()==0){
            JOptionPane.showMessageDialog(FrameUtama.getInstance(),
                    "Harga beli harus diisi!","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(txtQuantity.getText().length()==0 || 
                Integer.valueOf(txtQuantity.getText()) <= 0){
            JOptionPane.showMessageDialog(FrameUtama.getInstance(),
                    "Quantity harus diisi dan > 0!","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        btnLookup = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produk");

        jLabel2.setText("Harga Beli");

        jLabel3.setText("Quantity");

        jLabel4.setText("Sub Total");

        txtHargaBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHargaBeliKeyReleased(evt);
            }
        });

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });

        txtSubTotal.setEnabled(false);

        btnLookup.setText("...");
        btnLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubTotal)
                            .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if(validateForm()){
            if(pembelianDetail == null) pembelianDetail = new PembelianDetail();
            loadFormToDomain();
            dispose();
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        pembelianDetail = null;
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupActionPerformed
        Produk p = new ProdukSearchDialog().showDialog();
        if(p!=null){
            selectedProduk = p;
            txtProduk.setText(selectedProduk.getNama());
            txtHargaBeli.setText(TextComponentUtils.formatNumber(selectedProduk.getHargaPokok()));
        }
    }//GEN-LAST:event_btnLookupActionPerformed

    private void txtHargaBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaBeliKeyReleased
        calculateSubTotal();
    }//GEN-LAST:event_txtHargaBeliKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        calculateSubTotal();
    }//GEN-LAST:event_txtQuantityKeyReleased
    
    private void calculateSubTotal(){
        if(txtHargaBeli.getText().length()>0 && txtQuantity.getText().length()>0){
            BigDecimal hargaBeli = TextComponentUtils.parseNumberToBigDecimal(txtHargaBeli.getText());
            Integer qty = Integer.valueOf(txtQuantity.getText());
            BigDecimal subtotal = hargaBeli.multiply(new BigDecimal(qty));
            txtSubTotal.setText(TextComponentUtils.formatNumber(subtotal));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLookup;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSubTotal;
    // End of variables declaration//GEN-END:variables

}
