/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PenjualanSearchDialog.java
 *
 * Created on Jul 2, 2009, 1:37:05 PM
 */

package com.artivisi.pos.ui.dialog.transaksi;

import com.artivisi.pos.model.transaksi.Penjualan;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.artivisi.pos.util.POSTableCellRenderer;
import com.artivisi.pos.util.TextComponentUtils;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author ifnu
 */
public class PenjualanSearchDialog extends javax.swing.JDialog {

    private List<Penjualan> penjualans;
    private boolean isOk;
    private Penjualan selectedPenjualan;

    /** Creates new form PenjualanSearchDialog */
    public PenjualanSearchDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);
        tblPenjualan.setDefaultRenderer(Object.class, new POSTableCellRenderer());
        tblPenjualan.getSelectionModel().addListSelectionListener(new PenjualanSelectionListener());
        tblPenjualan.setAutoCreateColumnsFromModel(false);
    }

     public Penjualan showDialog(){
        penjualans = FrameUtama.getTransaksiService().semuaPenjualan();
        tblPenjualan.setModel(new PenjualanTableModel());
        setVisible(true);
        if(isOk == false) selectedPenjualan = null;
        return selectedPenjualan;
    }
    private class PenjualanTableModel extends AbstractTableModel{
        public int getRowCount() {
            return penjualans.size();
        }
        public int getColumnCount() {
            return 3;
        }
        public Object getValueAt(int rowIndex, int columnIndex) {
            Penjualan p = penjualans.get(rowIndex);
            switch(columnIndex){
                case 0 : return p.getId();
                case 1 : return p.getTanggal();
                case 2 : return p.getTotal();
                default: return "";
            }
        }
    }
    private class PenjualanSelectionListener implements ListSelectionListener{
        public void valueChanged(ListSelectionEvent e) {
            if(tblPenjualan.getSelectedRow()>=0){
                int index = tblPenjualan.convertRowIndexToModel(tblPenjualan.getSelectedRow());
                selectedPenjualan = penjualans.get(index);
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tanggal", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblPenjualan);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel1.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnBatal))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if(selectedPenjualan!=null){
            isOk =  true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(FrameUtama.getInstance(), "Pilih penjualan terlebih dahulu!"
                    ,"Warning",JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_btnOkActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        selectedPenjualan = null;
        dispose();
}//GEN-LAST:event_btnBatalActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        for(int i=0;i<tblPenjualan.getRowCount();i++){
            String current = tblPenjualan.getValueAt(i, 0).toString();
            if(current.toLowerCase().indexOf(txtSearch.getText().toLowerCase())>=0){
                tblPenjualan.getSelectionModel().setSelectionInterval(i, i);
                tblPenjualan.getColumnModel().getSelectionModel().setSelectionInterval(0, 0);
                TextComponentUtils.scrollToRect(tblPenjualan, i);
                break;
            }
        }
}//GEN-LAST:event_txtSearchKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
