/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PenjualanDetailDialog.java
 *
 * Created on Apr 30, 2009, 11:05:14 AM
 */

package com.artivisi.pos.ui.dialog.transaksi;

import com.artivisi.pos.model.master.Produk;
import com.artivisi.pos.model.transaksi.PenjualanDetail;
import com.artivisi.pos.ui.dialog.PencarianKecilDialog;
import com.artivisi.pos.ui.frame.FrameUtama;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author ifnu
 */
public class PenjualanDetailDialog extends javax.swing.JDialog {

    private Produk produk;
    private PenjualanDetail penjualanDetail;

    /** Creates new form PenjualanDetailDialog */
    public PenjualanDetailDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
    }

    public PenjualanDetail showDialog(){
        setVisible(true);
        return penjualanDetail;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        btnLookupProduk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtHarga = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produk");

        btnLookupProduk.setText("...");
        btnLookupProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupProdukActionPerformed(evt);
            }
        });

        jLabel2.setText("Kuantitas");

        jLabel3.setText("Harga");

        jLabel4.setText("Sub Total");

        txtSubTotal.setEnabled(false);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLookupProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSubTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnOk)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCancel))))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookupProduk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnOkActionPerformed
    private boolean validateForm(){
        if(txtProduk.getText().length()>0
                && txtHarga.getText().length()>0
                && txtQuantity.getText().length()>0
                && txtSubTotal.getText().length()>0){
            return true;
        } else {
            JOptionPane.showMessageDialog(FrameUtama.getInstance(),
                    "Semua Field harus diisi!!"
                    ,"Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void btnLookupProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupProdukActionPerformed
        List<Produk> produks = FrameUtama.getMasterService().semuaProduk();
        int row = new PencarianKecilDialog().showDialog(new ProdukTableModel(produks));
        if(row >=0){
            Produk p = produks.get(row);
            txtProduk.setText(p.getNama());
            txtHarga.setText(p.getHargaJual().toPlainString());
            produk = p;
        }
    }//GEN-LAST:event_btnLookupProdukActionPerformed
public class ProdukTableModel extends AbstractTableModel {

    private List<Produk> daftarProduk;

    public ProdukTableModel(List<Produk> daftarProduk) {
        this.daftarProduk = daftarProduk;
    }

    public int getRowCount() {
        return daftarProduk.size();
    }

    public int getColumnCount() {
        return 3;
    }

    @Override
    public String getColumnName(int col) {
        switch(col){
            case 0 : return "Kode barang";
            case 1 : return "Nama Barang";
            case 2 : return "Harga Beli";
            case 3 : return "Harga Jual";
            case 4 : return "Stok";
            default : return "";
        }

    }

    public Object getValueAt(int row, int col) {
        Produk p = daftarProduk.get(row);
        switch(col){
            case 0 : return p.getId();
            case 1 : return p.getNama();
            case 2 : return p.getHargaPokok();
            case 3 : return p.getHargaJual();
            case 4 : return p.getStok();
            default : return "";
        }
    }

    @Override
    public Class<?> getColumnClass(int columnIndex) {
        switch(columnIndex){
            case 2 : return BigDecimal.class;
            case 3 : return BigDecimal.class;
            case 4 : return Integer.class;
            default : return String.class;
        }
    }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLookupProduk;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField txtHarga;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSubTotal;
    // End of variables declaration//GEN-END:variables

}
