/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PenjualanAddDialog.java
 *
 * Created on Jul 2, 2009, 1:36:46 PM
 */

package com.artivisi.pos.ui.dialog.transaksi;

import com.artivisi.pos.model.master.Produk;
import com.artivisi.pos.model.transaksi.PenjualanDetail;
import com.artivisi.pos.ui.dialog.master.ProdukSearchDialog;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.artivisi.pos.util.TextComponentUtils;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author ifnu
 */
public class PenjualanAddDialog extends javax.swing.JDialog {

    private PenjualanDetail penjualanDetail;
    private Produk selectedProduk;

    /** Creates new form PenjualanAddDialog */
    public PenjualanAddDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);

        TextComponentUtils.setCurrency(txtHargaJual);
        TextComponentUtils.setNumericTextOnly(txtQuantity);
    }

    public PenjualanDetail showDialog(){
        setVisible(true);
        return penjualanDetail;
    }
    public PenjualanDetail showDialog(PenjualanDetail penjualanDetail){
        this.penjualanDetail = penjualanDetail;
        loadDomainToForm();
        setVisible(true);
        return this.penjualanDetail;
    }
    private void loadDomainToForm(){
        selectedProduk = penjualanDetail.getProduk();
        txtProduk.setText(selectedProduk.getNama());
        txtQuantity.setText(penjualanDetail.getKuantitas().toString());
        txtHargaJual.setText(
            TextComponentUtils.formatNumber(penjualanDetail.getHarga()));
        txtSubTotal.setText(
            TextComponentUtils.formatNumber(penjualanDetail.getSubTotal()));
    }
    private void loadFormToDomain(){
        penjualanDetail.setProduk(selectedProduk);
        penjualanDetail.setHarga(
            TextComponentUtils.parseNumberToBigDecimal(txtHargaJual.getText()));
        penjualanDetail.setSubTotal(
            TextComponentUtils.parseNumberToBigDecimal(txtSubTotal.getText()));
        penjualanDetail.setKuantitas(Integer.valueOf(txtQuantity.getText()));
    }

    private boolean validateForm(){
        if(txtProduk.getText().length() == 0 || selectedProduk==null){
            JOptionPane.showMessageDialog(FrameUtama.getInstance(),
                    "Pilih produk terlebih dahulu!","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(txtHargaJual.getText().length()==0){
            JOptionPane.showMessageDialog(FrameUtama.getInstance(),
                    "Harga beli harus diisi!","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(txtQuantity.getText().length()==0 ||
                Integer.valueOf(txtQuantity.getText()) <= 0){
            JOptionPane.showMessageDialog(FrameUtama.getInstance(),
                    "Quantity harus diisi dan > 0!","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        btnLookup = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produk");

        jLabel2.setText("Harga Jual");

        jLabel3.setText("Quantity");

        jLabel4.setText("Subtotal");

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });

        txtSubTotal.setEnabled(false);

        btnLookup.setText("...");
        btnLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLookup))
                    .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnBatal)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if(validateForm()){
            if(penjualanDetail == null) penjualanDetail = new PenjualanDetail();
            loadFormToDomain();
            dispose();
        }        
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        penjualanDetail = null;
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupActionPerformed
        Produk p = new ProdukSearchDialog().showDialog();
        if(p!=null){
            selectedProduk = p;
            txtProduk.setText(selectedProduk.getNama());
            txtHargaJual.setText(TextComponentUtils.formatNumber(selectedProduk.getHargaJual()));
            if(txtQuantity.getText().length()>0){
                BigDecimal subTotal  = TextComponentUtils.parseNumberToBigDecimal(txtHargaJual.getText())
                        .multiply(new BigDecimal(txtQuantity.getText()));
                txtSubTotal.setText(TextComponentUtils.formatNumber(subTotal));
            }
        }        
    }//GEN-LAST:event_btnLookupActionPerformed

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        if(txtHargaJual.getText().length()>0){
            BigDecimal subTotal  = TextComponentUtils.parseNumberToBigDecimal(txtHargaJual.getText())
                    .multiply(new BigDecimal(txtQuantity.getText()));
            txtSubTotal.setText(TextComponentUtils.formatNumber(subTotal));
        }
    }//GEN-LAST:event_txtQuantityKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLookup;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSubTotal;
    // End of variables declaration//GEN-END:variables

}
