/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SesiKassaDialog.java
 *
 * Created on Aug 9, 2009, 8:58:12 PM
 */

package com.artivisi.pos.ui.dialog.transaksi;

import com.artivisi.pos.model.master.Shift;
import com.artivisi.pos.model.transaksi.SesiKassa;
import com.artivisi.pos.ui.frame.FrameUtama;
import com.artivisi.pos.util.TextComponentUtils;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.Problems;
import org.netbeans.validation.api.Validator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationStrategy;

/**
 *
 * @author ifnu
 */
public class SesiKassaDialog extends javax.swing.JDialog {

    private SesiKassa sesiKassa;
    /** Creates new form SesiKassaDialog */
    public SesiKassaDialog() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        setLocationRelativeTo(null);

        TextComponentUtils.setCurrency(txtModal);

        cmbShift.setModel(new DefaultComboBoxModel(FrameUtama.getMasterService().semuaShift().toArray()));

        Shift shift = FrameUtama.getMasterService().shiftSekarang();
        if(shift == null){
            cmbShift.setSelectedItem(null);
            cmbShift.setEnabled(true);
        }
        initValidation();
    }

    private void initValidation(){
        ValidationGroup validationGroup = validationPanel.getValidationGroup();
        validationGroup.add(txtModal, ValidationStrategy.DEFAULT,
                Validators.REQUIRE_NON_EMPTY_STRING);
        //memastikan combobox dipilih

        if(cmbShift.isEnabled()){
            validationGroup.add(cmbShift, ValidationStrategy.DEFAULT, Validators.forComboBox(true, new Validator<String>() {

                public boolean validate(Problems problems, String componentName, String value) {
                    if(cmbShift.getSelectedItem() == null){
                        problems.add("Pilih salah satu " + componentName);
                        return false;
                    } else {
                        return true;
                    }
                }
            }));
        }

        validationPanel.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                if(validationPanel.isProblem()){
                    btnOk.setEnabled(false);
                } else {
                    btnOk.setEnabled(true);
                }
            }
        });
    }

    public SesiKassa showDialog(){
        txtPengguna.setText(FrameUtama.getPengguna().getId());
        txtKassa.setText(FrameUtama.getKassa().getId());
        jdcTanggal.setDate(FrameUtama.getMasterService().tanggalServer());
        setVisible(true);
        return sesiKassa;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPengguna = new javax.swing.JTextField();
        txtKassa = new javax.swing.JTextField();
        txtModal = new javax.swing.JTextField();
        cmbShift = new javax.swing.JComboBox();
        jdcTanggal = new com.toedter.calendar.JDateChooser();
        validationPanel = new org.netbeans.validation.api.ui.ValidationPanel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sesi Kassa Dialog");

        jLabel1.setText("Pengguna");

        jLabel2.setText("Kassa");

        jLabel3.setText("Shift");

        jLabel4.setText("Tanggal");

        jLabel5.setText("Modal");

        txtPengguna.setEnabled(false);

        txtKassa.setEnabled(false);

        cmbShift.setEnabled(false);

        jdcTanggal.setEnabled(false);

        btnOk.setText("OK");
        btnOk.setEnabled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKassa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbShift, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(validationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jdcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtModal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        sesiKassa = new SesiKassa();
        sesiKassa.setKasir(FrameUtama.getPengguna());
        sesiKassa.setKassa(FrameUtama.getKassa());
        sesiKassa.setModal(TextComponentUtils.parseNumberToBigDecimal(txtModal.getText()));
        if(cmbShift.isEnabled()){
            sesiKassa.setShift((Shift) cmbShift.getSelectedItem());
        } else {
            sesiKassa.setShift(FrameUtama.getMasterService().shiftSekarang());
        }
        sesiKassa.setTanggalLogin(FrameUtama.getMasterService().tanggalServer());
        FrameUtama.getTransaksiService().simpan(sesiKassa);
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbShift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.toedter.calendar.JDateChooser jdcTanggal;
    private javax.swing.JTextField txtKassa;
    private javax.swing.JTextField txtModal;
    private javax.swing.JTextField txtPengguna;
    private org.netbeans.validation.api.ui.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables

}
